### ISSUE TITLE
Confused about version triggering

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/json-ld-syntax#99] opened 2018-11-29 22:19 UTC
Current text states...
> <p>The first <code>context</code> encountered when processing a document which contains <code>@version</code> determines the <code>processing mode</code>, unless it is defined explicitly through an API option.</p>

However, the [1.1 playground](http://json-ld.org/playground-dev/) at least, seems to "switch" on the first context object even if it does *not* have an `@version`.

[For example](https://json-ld.org/playground-dev/#startTab=tab-nquads&json-ld=%7B%22%40context%22%3A%5B%22http%3A%2F%2Fschema.org%2F%22%2C%7B%22%40version%22%3A1.1%7D%5D%2C%22%40type%22%3A%22Person%22%2C%22name%22%3A%22bar%22%7D):
```json
{
  "@context": [
    "http://schema.org/",
    {
      "@version": 1.1
    }
  ],
  "@type": "Person",
  "name": "bar"
}
```

Throws:
```
jsonld.ProcessingModeConflict: @version: 1.1 not compatible with json-ld-1.0
```

So, my current proposal is to reword that text to:
> <p>Unless it is defined explicitly through an API option, the first <code>context</code> encountered when processing a document determines the <code>processing mode</code>.</p>

However, I'm not sure if that matches any pre-existing thoughts/plans for version triggering.

Does a `@context` *without* `@version` state that it should be processed as `json-ld-1.0`? Or since it hasn't stated an `@version` does it just fallback to the default set in the JSON-LD processor (which is currently 1.0 most places)?

The API's [4.1.2. Algorithm step 3.5](https://w3c.github.io/json-ld-api/#x4-1-2-algorithm) describes the scenario when `@version` has been set to *something* within the context, but doesn't explain what happens when one is *not* present.

So, beyond updating the text above, we may also need to address this in the API spec also.

**Comment by BigBlueHat** [comment] 2018-11-29 22:22
Discovered this while discussing #20. It also relates to #85 and #33.

**Comment by dlongley** [comment] 2018-11-29 22:42
jsonld.js needs to be fixed.

**Comment by azaroth42** [comment] 2019-01-17 19:41
Propose closing as duplicate of #85

**Closed** 2019-02-20 05:38 UTC
Labels: propose closing
