### ISSUE TITLE
Expanding @vocab properties consistently

### ISSUE THREAD

**Issue by pjohnston-wiley** [w3c/json-ld-syntax#56] opened 2018-08-22 22:56 UTC
(I wasn't sure if this was a syntax or an API issue. If i got the wrong one, please let me know and i will refile)

Consider the following:

```json
{
  "@context": {
    "@base": "http://example1.com/",
    "ex1": "http://example1.com/",
    "ex2": "http://example2.com/",
    "id": "@id",
    "fred": {
      "@id": "ex1:fred",
      "@type": "@vocab"
    },
    "barney": {
      "@id": "ex2:barney"
    },
    "mnemonic": "rdf:value"
  },
  "fred": [
    {
      "id": "barney",
      "mnemonic": "the sidekick"
    },
    "barney"
  ]
}
```

The counterintuitive result of expansion is:

```json
[
  {
    "http://example1.com/fred": [
      {
        "@id": "http://example1.com/barney",
        "rdf:value": [
          {
            "@value": "the sidekick"
          }
        ]
      },
      {
        "@id": "http://example2.com/barney"
      }
    ]
  }
]
```

In other words, one `barney` registers as a result of the top-level `@vocab` declaration, while the other registers as a result of the specific `barney` alias against the `fred` property of type `@vocab`. 

I understand _why_ this happens, the spec has different algorithms for strings on the right of a property vs objects, but it's a bit odd. To the lay reader (i.e. me), it seems like an inconsistent application. If the IRI expansion algorithm were able to take into account explicit aliases for `@vocab` properties, it could be made consistent, and a similar application to compaction would deliver a symmetric behavior.

The context, in terms of practical application, is that we maintain an overarching RDF model to govern our data and i would like the folks implementing our APIs to know as little about the RDF-ness of it as possible, which is where JSON-LD comes in. By using `@vocab` i was able to get implementers to omit a namespace qualifier on plain taxonomy values (the second `barney` in the original example), but as soon as they want to include anything richer they have to qualify it. Using the same context, to guarantee semantic consistency the example would have to be written as:  

```json
{
    "fred": [
      "barney",
      {
         "id": "ex2:barney",
         "mnemonic": "the sidekick"
      }
    ]
}
```
i.e. we have to qualify the second `barney` with `ex2` for it to work consistently, which means exposing API developers to the RDF-ness of our model, or breaking the connection.

**Comment by gkellogg** [comment] 2018-08-22 23:58
The reason for this is that `@id`, `@type` and properties are expanded using different bases. Typically, `@id` refers to something in the document, a property something in the vocabulary, and `@type` may be either. Thus, when you see "barney" as a string value of "fred", it is looked up relative to the vocabulary, as you have `"@type": "@vocab"` in the term definition for "fred"; if you used `"@type": "@id"`, it would be document relative. When the algorithm sees `"id": "barney"`, it is always interpreted document relative.

One way to fake out `@id` resolution is to use Compact IRIs. You can also make `@vocab` expand to be document relative in 1.1 by setting `"@vocab": ""`.

As for the _why_ of this, it comes from the observation that documents and vocabularies are really different things, and the expansion rules need to consider this. Also, `@vocab` is a powerful feature that can lead to such confusing results.

Here are some links to explore for the history:

* json-ld/json-ld.org#49 ([discussion](https://json-ld.org/minutes/2012-01-24/#topic-1)]

Turtle avoided this by always resolving relative IRIs to the base, and requiring prefixes (including the empty string "") for vocabulary terms. In JSON, the practice of using bare words as keys meant that we needed to interpret the intention of the JSON author to know what typically is used as a vocabulary term vs what is used for something within the document.

**Comment by azaroth42** [comment] 2018-08-24 18:15
I think the resolution to not fix json-ld-api#7 would be a precedent for close won't fix on this issue as well.

**Comment by pjohnston-wiley** [comment] 2018-08-25 00:56
Thanks @gkellogg for taking the time to provide the why and the suggestions, unfortunately they don't really help with the issue at hand (#wontfix notwithstanding). I'm not sure what the blank `@version` feature would do here - it's somewhat weird looking, and it doesn't appear to be implemented anywhere yet?

I am fine with making the `@context` more complicated – in our case it is generated programmatically anyway. What i am less inclined to do is make our API developers have to consider RDF-ness in an API context.

@azaroth42 One thing that allowed you to close [issue 7](https://github.com/w3c/json-ld-api/issues/7) was that there was a way to solve the problem using scoped contexts. So far i don't have a way to address this particular scenario. 

So... I went down a couple of rabbit holes. 

### Overriding `@id` behavior

Setting `id` to be of `@type` `@vocab` is syntactically valid, however the implementations currently ignore it.  This would actually make some sense to me.

```json
{
  "@context": {
    "@base": "http://example3.com/",
    "ex1": "http://example1.com/",
    "ex2": "http://example2.com/",
    "id": {
       "@id": "@id",
       "@type": "@vocab"
    },
    "fred": {
      "@id": "ex1:fred",
      "@type": "@vocab"
    },
    "barney": {
      "@id": "ex2:barney"
    },
    "mnemonic": "rdf:value"
  },
  "fred": [
    {
      "id": "barney",
      "mnemonic": "the sidekick"
    },
    "barney"
  ]
}
```

### Scoped context

Next i went the way of scoped contexts. This is not particularly elegant, but will work for the specific use case where the name of the alias matches the name portion of the IRI, and where you mostly operate under a single namespace IRI for the given property:

```json
{
  "@context": {
    "@version": 1.1,
    "@base": "http://example3.com",
    "ex1": "http://example1.com/",
    "ex2": "http://example2.com/",
    "id": "@id",
    "fred": {
      "@id": "ex1:fred",
      "@type": "@id",
      "@context": {"@base": "http://example2.com/"}      
    },
    "mnemonic": "rdf:value"
  },
  "fred": [
    {
      "id": "barney",
      "mnemonic": "wilma"
    },
    "barney"
  ]
}
```

Note i added `example3.com` to illustrate how this differs from the global default.

> @gkellogg this only works on the dev playground - am i right that your [distiller](http://rdf.greggkellogg.net/distiller) doesn't yet support 1.1 features?

However, outside of this narrow use case, you are stuck. For example, if you want to alias `barney` to `ex2:betty` there is no way to support this as far as i can tell.

**Comment by iherman** [comment] 2018-10-01 10:02
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-09-28-json-ld).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
4.2. @vocab property expansion<br/>
Rob Sanderson: Link: <a href="https://github.com/w3c/json-ld-syntax/issues/56">https://github.com/w3c/json-ld-syntax/issues/56</a><br/>
Rob Sanderson: This one is about the expansion of @vocab properties and the issue claims that it is counter-intuitive<br/>
… from my perspective, it goes back to #7 (won’t-fix) that the processing model for @type shouldn’t be able to customized<br/>
… more than allowing @container: @set<br/>
… to avoid monkeying around and overcomplicating<br/>
… the response is that that fixes #7, but you can’t fix this issue with scoped contexts<br/>
… but Gregg has an example that fixes it…<br/>
Gregg Kellogg: well…..<br/>
… his feeling is that he’s willing to do things in a context to hide this, but @base is restricted from being in a remote context, and that doesn’t satisfy him<br/>
… this is about discrepancies between vocabularies space and document space, where you can use @vocab: “”<br/>
… and that might get to a point where you’re not surprised, but there’s overlap with Manu’s blank-nodes as properties, where @vocab is a solution, but not a wide enough oe<br/>
… maybe we need to make that a bit wider, make it any relative IRI relevant to the document base<br/>
… in 1.0, you can generate an error with this, and we could make it document relevant, which widens what we can put in vocal, which handles both this and Manu’s request<br/>
Rob Sanderson: can you talk through why the first Barney expands this wy?<br/>
Gregg Kellogg: if we look at Barney, it’s value is a node definition. In any context, ex2:barney evaluates to the URl<br/>
… But fred has the value, with the value parnet<br/>
… string values are intended to be treated as an IRI within the vocab space, so if barney is the string value of fred, we evaluate barney as vocab-relevant<br/>
… there is no @vocab defined, but barney is a term, so we ill now interpret them as iris, so it’s got a value of ex2:barney<br/>
… so when we evaluate things in the vocabulary space, it will look to terms and compact IRIs<br/>
… so it satisfies the term use case<br/>
… when we look at it as ID, which makes it @id, which is in doc space, and we do not interpret things in that space relative to the vocabularies<br/>
… in document space, it cannot be a bare term, so we don’t evaluate it<br/>
… it could have been barney:, which would work.<br/>
… he asked why ID can’t be treated in the vocab space, and that goes back to our decision<br/>
… why didn’t we want terms to be values?<br/>
… since we allow compact terms?<br/>
… typically, where you see this conflation, you are closer to being in the use case where you’re defining a vocabulary<br/>
… where it does make sense<br/>
Rob Sanderson: was that clear?<br/>
Ivan Herman: so I’m not ashamed to say, no.<br/>
… It is because it is not complicated, bu what this means for us and readers, is that expansions, and the bifurcations, we should have that in a note and understand it<br/>
… frankly, I don’t have a clear idea how things work<br/>
… the other comment is that we should have a rule that when an issue is put in, and when it has an example, the example should be reduced.<br/>
… from the point of this issue, there are additional things that make things more complicated<br/>
Rob Sanderson: +1<br/>
Ivan Herman: we should really ask them to make it more simple and to be careful, since much here is not relevant<br/>
Adam Soroka: whatever comes out of this, we might really need a note lays out the spaces around expansion, since the suspicion is that this arises because it’s really hard to understand this<br/>
Gregg Kellogg: I think that the API document is fairly consistent is clear about this, and the people who are the most likely to be confused are unlikely to read this<br/>
… so we’re stuck with the JSON vocab, in turtle there are pnames or iris. In JSON, we can’t do that, so we need to discern the intent around meaning<br/>
… thus the bifurcation between the spaces<br/>
… it’s laid out, and it’s easy to get lost, and adding another note in syntax documents.<br/>
… how much detail to be need to get into?<br/>
… we need a primer<br/>
… and we need a champion for that primer<br/>
Ivan Herman: I get the problem, and it’s not 1.0, it’s just…terrible.<br/>
… and I don’t think it needs to be in the specification, and a primer would be the ideal place for it.<br/>
… authors will never read the API, and I don’t want to. I just want to put data in JSON-LD<br/>
… that’s why the primer is required.<br/>
… otherwise people will be lost<br/>
Jeff Mixter: the explanation is helpful, and it would be helpful to have the example to be recreated to be realistic, and it’s really confusing with freds and barneys<br/>
… it might be better to have real-world examples<br/>
Rob Sanderson: a complication with #33<br/>
Rob Sanderson: <a href="https://github.com/w3c/json-ld-api/issues/33">https://github.com/w3c/json-ld-api/issues/33</a><br/>
Rob Sanderson: It would be nice to have the Uris compact to not just ID, but also to @id. Doesn’t this mean changing the space?<br/>
Gregg Kellogg: the way I take this option is to not compact to allow properties, but not values<br/>
… that things would remain in their expanded state.<br/>
… doing this wouldn’t add additional space<br/>
… it’s how you interpret string values. If you’ve got an object, it’s unambiguous<br/>
Rob Sanderson: If the context wanted ID: barney to be compacted to id: barney, and another term compacted to a string, then those two otherwise identical lines would have different value spaces<br/>
Gregg Kellogg: if you were able to specify the value space of a term, as in the first comment of #33…I think the issues comes down to wanting to specifiy for a property when compacting, you want to compact the term, but not the value.<br/>
… if you do this, it continues to be unambiguous, …something about strings…<br/>
Rob Sanderson: is there a proposal?<br/>
Gregg Kellogg: do we need a issue to change the rules about @vocab to use relative IRIs in document space<br/>
… I can create that issue<br/>
Ivan Herman: I would like to move this to face-to-face<br/>
Gregg Kellogg: sure<br/>
Rob Sanderson: sure<br/>
Adam Soroka: could we leave a note for the primer?<br/>
… maybe a label?<br/>
… about the spaces?<br/>
Gregg Kellogg: we should create an issue for the primer about that<br/>
Rob Sanderson: gregg, create the issue about vocabs, adam, about the primer, and we’ll defer this to face-t-face<br/>
Adam Soroka: +1 to that!<br/>
</details>

**Comment by iherman** [comment] 2018-10-26 10:21
Here is the minimal example that has the problem area focused on only:

```json
{
  "@context": {
    "fred": {
      "@id": "http://a.b.c",
      "@type": "@vocab"
    },
    "barney": {
      "@id": "abc:def"
    }
  },
  "fred": "barney"
}
```

**Comment by iherman** [comment] 2018-10-27 07:07
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-10-26-json-ld#section4).

- `RESOLVED:  Make #56 editorial to add a "@type":"@vocab" example and otherwise no change`
<details><summary><i class="differentiate">View the transcript</i></summary>
Gregg Kellogg: the concern is that the same term expands differently in different places<br/>
… gkellogg then describes the example in the issue<br/>
Rob Sanderson: the example has two triples in it:<br/>
Benjamin Young: triples from the playground from the first example in #56<br/>
Benjamin Young: &lt;<a href="http://example1.com/barney>">http://example1.com/barney></a> <rdf:value> "the sidekick" .<br/>
Benjamin Young: _:b0 <<a href="http://example1.com/fred>">http://example1.com/fred></a> <<a href="http://example1.com/barney>">http://example1.com/barney></a> .<br/>
Benjamin Young: _:b0 <<a href="http://example1.com/fred>">http://example1.com/fred></a> <<a href="http://example2.com/barney>">http://example2.com/barney></a> .<br/>
Ivan Herman: I would say that in the second case (barney is a string) it’s the defn of barney that comes in<br/>
… nothing to do with that fred is defined by vocab<br/>
Gregg Kellogg: no, it does have to do with<br/>
… our rules are intentionally different for different kinds of values<br/>
… the complaint is that the rules for resolving IRIs vary<br/>
… in the example the value space of fred is vocab<br/>
… the fact that there is an entry in the vocab space for barney means nothing when we use barney as an ID.<br/>
Adam Soroka: that’s the two different spaces<br/>
Gregg Kellogg: unless it happens to be used in a CURI<br/>
Ivan Herman: this is confusing<br/>
Gregg Kellogg: in 1.0 there is a distinction between the vocabulary (properties, types) and values, which come from the document.<br/>
… if you have a term in the vocab with a name that is used as instance data, in each position they are resolved differently.<br/>
Benjamin Young: a remix of the example of #56 using 2 contexts in <a href="http://tinyurl.com/y7wpjogw">http://tinyurl.com/y7wpjogw</a><br/>
Gregg Kellogg: we’re getting back into deep history of 1.0 here. Qe felt there are good reasons to make this distinction, but we may have been wrong, of course<br/>
Adam Soroka: ivan is now showing examples on the projector, see <a href="http://tinyurl.com/yclwe2ax">http://tinyurl.com/yclwe2ax</a><br/>
Gregg Kellogg: when you have a doc, you ascribe meaning by bring properties and types to it.<br/>
… but you would want to resolve relative value URIs differently than vocab terms<br/>
Rob Sanderson: but this kind of problematic situation shouldn’t arise<br/>
Benjamin Young: sometimes you don’t get a choice<br/>
Rob Sanderson: you should be able to avoid it by inverting the order of multiple contexts, if they colliding in this way between them<br/>
Ivan Herman: in the first example with barney, <a href="http://example1.com/">http://example1.com/</a> is used for base and the first appearance of fred<br/>
Gregg Kellogg: the fact that barney is a term in the context doesn’t affect value expansion<br/>
Ivan Herman: if I change the base, various changes result<br/>
… we could pare down the example<br/>
Benjamin Young: this could confuse naive devs<br/>
Rob Sanderson: you should never get this to begin with<br/>
… what would be the use of interpreting barney as the same thing in the example<br/>
… you wouldn’t construct that data.<br/>
Benjamin Young: [uses his hands to construct a list of annotations]<br/>
… one past use case we’ve gotten is when you start with a list of ids,then you reference down into a list of inclusions.<br/>
… the use case from which this current issue came is gathering that up into a packaged graph with lots of graphs about the same stuff<br/>
Rob Sanderson: <a href="http://tinyurl.com/yb3olq5y">http://tinyurl.com/yb3olq5y</a><br/>
Benjamin Young: in JSON-LD we are constantly using many contexts, that raises the likelihood of this<br/>
Adam Soroka: more discussion about whether or not this situation can realistically arise<br/>
Rob Sanderson: the data in the OP example is meaningless<br/>
Adam Soroka: ivan brings more examples to the projector<br/>
Ivan Herman: here is a minimal situation to display the problem<br/>
Ivan Herman: A simpler version of the example:<br/>
{<br/>
<b>"@context":</b> {<br/>
<b>"fred":</b> {<br/>
<b>"@id":</b> "<a href="http://a.b.c",">http://a.b.c",</a><br/>
<b>"@type":</b> "@vocab"<br/>
},<br/>
<b>"barney":</b> {<br/>
<b>"@id":</b> "abc:def"<br/>
}<br/>
},<br/>
<b>"fred":</b> "barney"<br/>
}<br/>
(see <a href="http://tinyurl.com/y78bzssn)">http://tinyurl.com/y78bzssn)</a><br/>
Adam Soroka: agreement that ivan’s new example minimally demonstrates the problem<br/>
Gregg Kellogg: why does one want to create terms with '@type':"@vocab" to begin with?<br/>
Ivan Herman: we should have a very clear example of this and explanation of this in the docs<br/>
Gregg Kellogg: I think we have examples<br/>
Ivan Herman: with lots of explanation<br/>
Gregg Kellogg: we have a document space and a vocab space, and the only time document terms get resolved in vocab space is in compact IRIs<br/>
… and when the term used as the property is defined as '@type':"@vocab"<br/>
Benjamin Young: this example wasn’t contrived—it came out of extant tooling<br/>
Adam Soroka: disagreement about how responsible users are to avoid these kinds of colisions when using other people context’s<br/>
Ivan Herman: Patrick (the OP) is a very expert user. What about the less-expert users?<br/>
… it’s a return to what I earlier said: what if I am semweb literate, and I come to this, and I can’t make my graph work sanely in JSON-LD<br/>
Benjamin Young: even with Patrick’s expertise he hit this problem, and not by trying to develop a curious example<br/>
… it was normal work<br/>
Gregg Kellogg: this might stem from divergent missions<br/>
… surprising that someone trying to turn Turtle into JSON-LD doesn’t find that obvious<br/>
Ivan Herman: might need to push this into the primer<br/>
… the doc as is tried to make it usable for JSON devs<br/>
… we may need to write from the other direction<br/>
… for RDF folks coming to JSON<br/>
Rob Sanderson: in Patrick’s defense, there is no good example for this<br/>
Gregg Kellogg: I can try to write this up<br/>
… one concern: we are still getting to “own” JSON-LD<br/>
… we all need to get to an adequate mastery level to be able to talk about this<br/>
… we could try assigning issues to people who raise them<br/>
Proposed resolution: Make #56 editorial to add a "@type":"@vocab" example (Rob Sanderson)<br/>
Adam Soroka: +1<br/>
Proposed resolution: Make #56 editorial to add a "@type":"@vocab" example and otherwise no change (Rob Sanderson)<br/>
Rob Sanderson: +1<br/>
Simon Steyskal: +1<br/>
Benjamin Young: +1<br/>
Gregg Kellogg: +1<br/>
Adam Soroka: +1<br/>
Harold Solbrig: +1<br/>
Resolution #4: Make #56 editorial to add a "@type":"@vocab" example and otherwise no change<br/>
</details>

**Comment by iherman** [comment] 2018-12-08 05:52
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-12-07-json-ld#section4).

- `RESOLVED:  close issues 56, 77, and 102 as having been addressed by recent merges`
<details><summary><i class="differentiate">View the transcript</i></summary>
Gregg Kellogg: issue 56 - this was looking for examples to indicate unexpected behavior when type is a vocab<br/>
… i think ball was in Ivan’s court whether the examples were sufficient<br/>
… we are not closing the issue until after the PR, so question is whether we are ready to close<br/>
… we added 2 examples<br/>
… next issue is 77, disambiguate uses of @type<br/>
… Webex seems to have some problems with this meeting, especially if changing focus on my computer<br/>
… we discussed adding @datatype, instead decided to add text around different uses of @type<br/>
… are people satisfied with wording?<br/>
Gregg Kellogg: use of @none regarding language<br/>
… in seeming conflict with requirement that language has to be string, @none didn’t specify<br/>
… fixed that wording making clear that @none has to be a string<br/>
Benjamin Young: these are tagged proposed closing<br/>
… we need to decide if ready to close<br/>
Adam Soroka: I wanted to mention the @datatype issue - I’m okay with this, but we may need a gitHub tag for whenever issues about @type comes up<br/>
… this will be a way to verify that spec wording update is enough to minimize confusion<br/>
Gregg Kellogg: <a href="https://github.com/w3c/json-ld-wg/issues/24">https://github.com/w3c/json-ld-wg/issues/24</a><br/>
Gregg Kellogg: I did raise issue 24 about surfacing the minutes on this topic like we did in Community Group<br/>
… could we do this?<br/>
… was useful in community group<br/>
Ivan Herman: minutes cleanup is done by me, and summarizing each meeting may not be a good idea<br/>
Gregg Kellogg: there is a scribe tool that builds summaries and indexes automatically<br/>
Benjamin Young: it works on issues and action lists at top/bottom of each meeting minutes<br/>
Gregg Kellogg: the good thing is it aggregates all minutes on each issue<br/>
Benjamin Young: I will take an action to investigate to see if we can build index of minutes by issue<br/>
… I think this is a good idea<br/>
Gregg Kellogg: will work with bigbluehat on this since I worked on CG<br/>
Benjamin Young: can we close these 3 issues<br/>
… 56, 77 and 102 ?<br/>
Ivan Herman: can we do a resolution to close these 3 issues?<br/>
Proposed resolution: close issues 56, 77, and 102 as having been addressed by recent merges (Benjamin Young)<br/>
Ivan Herman: +1<br/>
Gregg Kellogg: +1<br/>
Tim Cole: +1<br/>
Benjamin Young: +1<br/>
David Newbury: +1<br/>
Pierre-Antoine Champin: +1<br/>
Resolution #1: close issues 56, 77, and 102 as having been addressed by recent merges<br/>
</details>

**Closed by iherman** 2018-12-08 05:52 UTC
Labels: propose closing

**Comment by pjohnston-wiley** [comment] 2018-12-09 02:44
Belatedly, thank you all for the time you spent on this. Closing. chz p
