### ISSUE TITLE
what's the use of "@container": ["@id", "@set"]

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/json-ld-syntax#140] opened 2019-02-26 10:26 UTC
https://w3c.github.io/json-ld-syntax/#example-82-indexing-data-in-json-ld-by-node-identifiers-with-set-representation
Maybe I'm missing something but what use is `"@container": ["@id", "@set"]`?
I think that with `@id` indexing, every `@id` gets one JSON object.
So `@set` will turn them all into singleton arrays: what is the use of that?

**Comment by ajs6f** [comment] 2019-02-26 14:32
@VladimirAlexiev The idea is to be able to force the shape of the resulting JSON. One of JSON-LD's most important uses is "annotating" vanilla JSON so that it can be understood in a semantic context. In this use case it's not always possible to decide to use an array or a single value-- that decision may have already been made.
Another way to put it: JSON-LD context authors may need to ensure that their JSON results match a certain expected JSON structure (e.g. defined by an API spec) so that clients who only understand JSON (not JSON-LD) have no more trouble than they must parsing the JSON.

**Comment by dlongley** [comment] 2019-02-26 17:05
I recommend we have this sort of reasoning added to the feature descriptions in the spec (where possible).

**Comment by VladimirAlexiev** [comment] 2019-02-26 21:49
@ajs6f without such annotation, the jsonld processor will unpack the singleton arrays. 

In this case all the arrays are singletons by necessity, so what use it is to have that annotation?

**Comment by gkellogg** [comment] 2019-02-26 22:03
Note that `["@id", "@set"]` really only helps the compaction process. When expanding, a processor will treat a single value vs an array of that single value the same way. The need is to make sure that when framing and/or compacting, that the resulting serialization will always use the array form in this case, which makes the programming logic to access such things easier.

**Comment by ajs6f** [comment] 2019-02-27 17:09
@VladimirAlexiev Does that help answer the question?

**Comment by azaroth42** [comment] 2019-03-29 17:17
Closed by resolution: https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-03-29-json-ld#resolution3

**Closed by azaroth42** 2019-03-29 17:17 UTC
Labels: propose closing, spec:editorial

**Comment by iherman** [comment] 2019-03-29 17:19
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-03-29-json-ld#section4-3).

- `RESOLVED:  Close #140 as a feature not a bug - no need to use it if you don’t want it, and gives consistency`
<details><summary><i class="differentiate">View the transcript</i></summary>
4.3. @container [@id, @set]<br/>
Rob Sanderson: Link: <a href="https://github.com/w3c/json-ld-syntax/issues/140">https://github.com/w3c/json-ld-syntax/issues/140</a><br/>
Rob Sanderson: this issue questions the relevance of @container [@id, @set]<br/>
… many people have answered, in the line of “it’s a feature, not a bug”<br/>
Proposed resolution: Close #140 as a feature not a bug - no need to use it if you don’t want it, and gives consistency (Rob Sanderson)<br/>
Rob Sanderson: +1<br/>
Gregg Kellogg: +1<br/>
Dave Longley: +1<br/>
Tim Cole: +1<br/>
David Newbury: +1<br/>
Gregg Kellogg: it is about consistency and orthogonality, despite the lack of use case<br/>
Pierre-Antoine Champin: +1<br/>
Ruben Taelman: +1<br/>
Adam Soroka: +1<br/>
Ivan Herman: +1<br/>
Resolution #3: Close #140 as a feature not a bug - no need to use it if you don’t want it, and gives consistency<br/>
David I. Lehn: +1<br/>
</details>

**Comment by VladimirAlexiev** [comment] 2019-04-07 16:40
@aj6f and @gkellogg thanks for the explanations!
In this case, as @dlongley said, it'd be useful to add a similar explanation to the spec.

Wow, the prev comment demonstrates an enviable level of automation on part of the w3c :-)
