### ISSUE TITLE
Disambiguate uses of @type

### ISSUE THREAD

**Issue by azaroth42** [w3c/json-ld-syntax#77] opened 2018-10-05 17:48 UTC
Related to json-ld-api#33, we discussed on 2018-10-05 WG call the distinction between `@type` as a baked in alias for `rdf:type`, and `@type` as a function of the syntax for specifying the data type of the JSON object (resource vs literal, and type of literal), via the context.

There was general agreement that this was a common source of confusion, and could be ameliorated for expansion by introducing an alias (for example `@datatype`) but that this would add to confusion in compaction, as it would replace `@type` everywhere.  A more robust change would require a change to the specification to allow either `@type` or `@datatype` as the way to specify the data type, however that is a significant addition that should be considered in detail.

Further, one might introduce `type`: `rdf:type` in a context, rather than use the more magical `@type`. This approach would also impact the specifications, but would follow from the rejection of the `@label` syntactic sugar  in #6.

**Comment by iherman** [comment] 2018-10-27 07:03
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-10-26-json-ld#section2).

- `RESOLVED:  add @datatype for use with value nodes that would be a synonym only in those situations for @type`
<details><summary><i class="differentiate">View the transcript</i></summary>
Ivan Herman: can @container be used with @type to separate string, dates, etc?<br/>
… if so that is again an argument to deconflate all the meanings of @container<br/>
Gregg Kellogg: might make sense but isn’t very useful<br/>
… the datatype for all variations would be rdf:HTML, so you wouldn’t be able to also work by languages<br/>
Ivan Herman: right. but even gkellogg had to think about whether you can use @type with @container, which tells us that we need to simplify<br/>
… a container-mapping for @dataype — it’s not clear whether it would be useful<br/>
Rob Sanderson: if rdf:Literal is the datatype…<br/>
… if you had some HTML, some strings, maybe you can sort it out then<br/>
Ivan Herman: so mapping via datatype is questionable<br/>
Gregg Kellogg: I understand the proposal to be a new keyword @datatype to be used in contexts to signal datatypes, as @type does today<br/>
… letting us mark that usage of @type as obsolete<br/>
Ivan Herman: even today, you could use it via aliasing.<br/>
Gregg Kellogg: compaction wouldn’t do what you want if you did that<br/>
Ivan Herman: we have an example from Publishing WG where the alias would be useful, and round tripping not necessary<br/>
Proposed resolution: add @datatype for use with value nodes that would be a synonym only in those situations for @type (Rob Sanderson)<br/>
Rob Sanderson: +1<br/>
Ivan Herman: +1<br/>
Adam Soroka: +1<br/>
Harold Solbrig: +0<br/>
Simon Steyskal: +1<br/>
Gregg Kellogg: +0.5<br/>
Adam Soroka: Assuming bigbluehat is +1<br/>
Resolution #2: add @datatype for use with value nodes that would be a synonym only in those situations for @type<br/>
</details>

**Comment by BigBlueHat** [comment] 2018-11-06 18:21
> Ivan Herman: we have an example from Publishing WG where the alias would be useful, and round tripping not necessary

You'll have to expand on this @iherman. I'm not sure why the JSON-LD in the Publishing WG's current spec should be any less round-trip-able than any other JSON-LD. Wiley's use of JSON-LD is part of a wider internal and external RDF-based ecosystem, so it'd be terrible to have an alias gum up the gears.

Additionally, I'm not sure `@datatype` clarifies things any more than `@type`'s usage in specific proximity to `@value` did/does.

As in:
```json
{
  "@value": "<strong>markup!</strong>",
  "@datatype": "rdf:HTML"
}
```
doesn't seem any clearer than:
```json
{
  "@value": "<strong>markup!</strong>",
  "@type": "rdf:HTML"
}
```
and ultimately means someone somewhere will try to write:
```json
{
  "@datatype": "Organization",
  "name": "GitHub"
}
```
which, if I understand the proposal (i.e. "synonym only in those situations") would fail...but for reasons unclear to the person writing the JSON.

I'd actually have been 👎 on this had I been on the call. I'm just not sure what value this new bit of syntax is bringing vs. the confusion risk to folks typing JSON. Sorry folks...

**Comment by iherman** [comment] 2018-11-07 07:41
The behaviour of `@type`, when applied on an object, is fundamentally different than when applied on a literal. I believe the fact that two behaviours are conflated in the same keyword is a bug in the specification, and this manifested itself in a number of issues that were raised.

It can be disputed whether adding an alias for `@datatype` is the best solution; I believe making it clear to users that, on long term, using `@type` on a literal would not be allowed is important.

As for publishers: you may be right. But the feeling I have is that an overwhelming majority of user agents (including schema.org in this sense) do not do round tripping. They just consume the data, convert it into, say, triples, and take it from there. I may be wrong with my assessment.

**Comment by BigBlueHat** [comment] 2018-11-07 21:02
What we're specifically addressing with this issue is the variation between "node type" and "value type" as described in this note and it's following example: https://w3c.github.io/json-ld-syntax/#h-note-12

We should keep in mind that the "value type" construction is actually quite rare in *data* "in the wild" and frequently abstracted away via the `@context` so that the JSON data document is simpler. Consequently, developers pragmatically only use the `{"@value": "", "@type": ""}` construction within data when they know they need to define a datatype on the *string* encoded in `@value`.

Also, we've made RDF round tripping the reason for not adding certain requested features, so using it now as something people "do not do" seems dangerous--especially since it's something Wiley specifically does with our JSON-LD data.

Regardless, introducing an alias that causes processing confusion in the hopes that it's somehow clearer than the existing rare contextual use of the `@value`/`@type` combo seems dangerous.

**Comment by azaroth42** [comment] 2018-11-08 19:08
I disagree. Value **nodes** occur in every JSON-LD document. The fact that the {`@value` / `@type` } pattern is not common is due in part to the confusion engendered by overloading `@type`. In IIIF (and in the Annotation work IIRC, though it might not have come up explicitly) we avoided having to deal with value **type** constructions at all costs, even when it would otherwise be useful.  If you ask for expanded form, you'll get the value type construction everywhere, of course.

I don't follow the round tripping issue. Is it that it would be indeterminate whether the original JSON used `@type` or `@datatype`? That seems very minor to me, given that the compact form does often hide this in the context.

To me, we have seen the results of this conflation over and over again with the various issues that have been raised around type coercion for classes rather than datatypes. I don't think there's any "somehow" about it -- the proposal that `@type` is an alias for rdf:type, `@datatype` is the expression of the data type of a literal value is very clear.

**Comment by gkellogg** [comment] 2018-11-09 17:46
Also, see https://json-ld.org/minutes/2011-12-13/#topic-4 and https://github.com/json-ld/json-ld.org/issues/31.

**Comment by iherman** [comment] 2018-11-09 18:16
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-11-09-json-ld#section3-1).

- `RESOLVED:  bigbluehat & gkellogg to come up with rewording for 4.2, and new section for 9 for keywords, for review as to whether this will solve confusion without technical change`
<details><summary><i class="differentiate">View the transcript</i></summary>
3.1. @type / @datatype<br/>
Rob Sanderson: link: <a href="https://github.com/w3c/json-ld-syntax/issues/77">https://github.com/w3c/json-ld-syntax/issues/77</a><br/>
Rob Sanderson: two issue that came up as being particularly interesting.<br/>
… we should focus on them and try to come to some consensus<br/>
Rob Sanderson: related to issue 31 and the feeling at the time was that the overloading of @type was confusing<br/>
… we proposed to add a new way in 1.1 to distinguish a datatype<br/>
… that would clear up some of the confusion<br/>
… decided to use @datatype but need to discuss more<br/>
… ivan and I are on the pro side of @datatype. Ben is against it.<br/>
Gregg Kellogg: I have mixed opinions. If we had thought about this originally it would have made sense but we did not. Now we need to consider backwards compatibility<br/>
… creating an alias of datatype to @datatype might help<br/>
… we would lose the @dataype alias with expansion<br/>
… just keep in mind that it will disappear with any transformation<br/>
Rob Sanderson: Example today: {"@type": "foaf:Person", "foaf:age": {"@value": "42", "@type": "xsd:integer"}}<br/>
Rob Sanderson: Proposed additional synonymous construct: {"@type": "foaf:Person", "foaf:age": {"@value": "42", "@datatype": "xsd:integer"}}<br/>
Pierre-Antoine Champin: I assumed that @type usage had been talked about in the 1.0 dev. Wanted to hear why the decision was made to not split the hair.<br/>
Gregg Kellogg: <a href="https://json-ld.org/minutes/2011-10-18/#topic-2">https://json-ld.org/minutes/2011-10-18/#topic-2</a><br/>
Gregg Kellogg: there was an explosion of keywords back in the day and we determined that some were redundant or very similar. we did have an @datatype and decided to merge them back in 2011.<br/>
… this was decided prior to the close alignment to RDF<br/>
Gregg Kellogg: <a href="https://json-ld.org/minutes/2011-12-13/#resolution-5">https://json-ld.org/minutes/2011-12-13/#resolution-5</a><br/>
Gregg Kellogg: Quote from Manu - “what convinced me most was Markus’ argument that we should make it as simple as possible without losing functionality”<br/>
Gregg Kellogg: <a href="https://github.com/json-ld/json-ld.org/issues/31">https://github.com/json-ld/json-ld.org/issues/31</a><br/>
Gregg Kellogg: From lanthaler - “I don’t think we can argue that we reduce the amount of invalid data that is created by having two different keywords. I’d argue that we increase the problem because people might put @datatype in the wrong place vs. @type.”<br/>
Benjamin Young: which camps are we making it easier or harder for. it is rare to see this type of thing in the actual data. hearing what Gregg would have to do to make it works seems a bit too much to ask. The type coercion is valid but might be a fringe use case<br/>
… concerned about the ramifications of doing this<br/>
David Newbury: when trying to learn JSON-ld and learning that @type means 2 different things. Long time to wrap my head around using the wrong keyword with different meaning.<br/>
Rob Sanderson: I had the same experience. In the IIIF world we had 5 editors and we were trying to use type coercion on classes but we found that it did not work<br/>
… also confuses a vendor we are working with<br/>
… no evidence that it is more confusing to separate them<br/>
… you could compact and expand to create valid JSON-ld. round-tripping seems like not an issue.<br/>
Benjamin Young: I agree that @type is confusing. What I am concerned about is if adding @datatype makes it any more clear<br/>
… very robust explanation would help<br/>
… this could create a new set of confusion<br/>
Ivan Herman: one thing we need to remind ourselves is that our only requirement is that a valid 1.0 is valid 1.1<br/>
… round tripping in not really an issue<br/>
… what happens in 1.1 with processing the data.<br/>
… pure JSON users will likely have issue in general. Diff between classes and literals are already somewhat confusing.<br/>
… separating @type and @datatype makes it clear that there is a distinction<br/>
Pierre-Antoine Champin: could we specify that @type is used for resources, and @datatype is used for literals, but that @type can be used as an alias for @datatype<br/>
Gregg Kellogg: we could make the move to use @datatype and allow for @type for backwards compatibility. The issue is the processor, which is currently either 1.0 or 1.1 mode.<br/>
… do we change the default processor to 1.1 and require a way to switch to change to 1.0<br/>
Benjamin Young: +1 to what Gregg was saying. The versioning is a problem outside of the problem of what is better solution. There is a risk whenever you change things.<br/>
… what is the impact on consumers of JSON-ld when the consumers are consuming pure JSON not Graph data<br/>
Rob Sanderson: sounds like there are 4 or 5 folks that are in favor and 1 against and 1 neutral (leaning against). The arguments against are significant (the 1.0 vs 1.1 processing issue)<br/>
… If Ben and Gregg come up with a clear/complete definition of @type and a further rewording around type coercion. Then we can read them over, assess the definition and see if the text of the spec is clear enough to explain what the difference is and how to implement it<br/>
… we can then decide if the documentation is sufficient or if we need to further consider splitting them<br/>
Gregg Kellogg: <a href="https://www.w3.org/TR/json-ld11/#syntax-tokens-and-keywords">https://www.w3.org/TR/json-ld11/#syntax-tokens-and-keywords</a><br/>
Gregg Kellogg: is the current wording not clear enough? what are you looking for?<br/>
… could we raise issue about the current documentation about what is not clear enough<br/>
Rob Sanderson: nodes are meaningless to people with RDF hats on.<br/>
Gregg Kellogg: are you looking for the current docs to be improved or for something new<br/>
Rob Sanderson: 1.7 is fine. 4.2.1 needs more clarity<br/>
… it is not a technical issue it is a learning/implementation issue<br/>
… 4.2 is the problem<br/>
… splitting out @type into how to use for Classes and for Literals<br/>
Gregg Kellogg: what about further definition of other keywords<br/>
Rob Sanderson: a section in 9 about keywords and gives full definition.<br/>
Benjamin Young: more than happy to help rewording. confusion between Value instead of Literal.<br/>
Ivan Herman: we should make is more explicit that there is very clear distinction between classes and literals in JSON-ld<br/>
Rob Sanderson: +1 to Ivan<br/>
David Newbury: need a JSON person primer<br/>
Proposed resolution: bigbluehat &amp; gkellogg to come up with rewording for 4.2, and new section for 9 for keywords, for review as to whether this will solve confusion without technical change (Rob Sanderson)<br/>
Rob Sanderson: +1<br/>
Jeff Mixter: +1<br/>
Ivan Herman: +1<br/>
Benjamin Young: +1 (noting it might include more revising elsewhere)<br/>
Gregg Kellogg: +1<br/>
David Newbury: +1<br/>
Pierre-Antoine Champin: +1<br/>
Resolution #2: bigbluehat & gkellogg to come up with rewording for 4.2, and new section for 9 for keywords, for review as to whether this will solve confusion without technical change<br/>
</details>

**Comment by msporny** [comment] 2018-11-09 19:09
> RESOLVED: bigbluehat & gkellogg to come up with rewording for 4.2, and new section for 9 for keywords, for review as to whether this will solve confusion without technical change

I'm glad this is where things are now as the whole move to `@datatype` seems like a solution for a problem that very few people are having. We considered all of this in JSON-LD 1.0 and the conclusion we came to was that adding more @keywords was something we should avoid doing because of the cognitive overhead it created for developers.

**Comment by ericprud** [comment] 2018-11-10 20:53
> The whole move to @datatype seemed like a solution for a problem that very few people are having.

I don't know that I'm the target audience but the major confusion for me that pushed JSON-LD from i'll-grok-the-spec to i'll-fiddle-around-until-it-works was the fact that @type had so many different uses. Sure they don't appear in the same place so there's technically no conflict but minification of the vocabulary has real cognitive costs.

**Comment by msporny** [comment] 2018-11-12 14:11
> I don't know that I'm the target audience

You are definitely not the target audience. You know too much. :)

**Comment by ajs6f** [comment] 2018-11-12 15:14
I originally voted for this change, but I'm realizing that there is more going on here than I understood. Just some general thoughts from listening to the discussion:

I understand us to have several target audiences (and none of us, I guess, are well representative of any of them :grin: ), but for this issue, one obvious division is between people going RDF->JSON and those going the other way (who, I would think, outnumber the former). Another is between context authors and people who use someone else's context (I would expect _many_ more of the latter, at least for some time to come).

RDF->JSON folks will start out with the distinction between ` rdf:type` and literal type. They will seek to express it. This feature will be convenient to them for that purpose. But folks going the other way won't necessarily be expecting that kind of distinction, unless they happen to use languages with explicit syntax for value objects (not in the [JSON-LD sense](https://www.w3.org/TR/json-ld/#dfn-value-object), in the [more general computer science sense](https://en.wikipedia.org/wiki/Value_object)), and even then, RDF literal datatypes aren't the equivalent of general value objects. Of the folks going JSON->RDF, only the context-writers face this confusion.

Some of the debate I'm hearing is about whether we do well for the people writing contexts to make the distinction very obvious via keywords (and thus hopefully avoid the confusions around type coercion which @azaroth42 has noticed and which I have also seen) or whether, for people who don't need this distinction in their own systems, we do ill to make them notice it for this one task. 

JSON, as I understand it, doesn't have a first-class notion like `rdf:type`. But JSON APIs, which are a prime use case for annotation with contexts that are _not_ someone else's, implicitly have a lot of `rdf:type`s. We can't easily offer this new distinction (`@type` vs. `@datatype`) as meeting the distinction between types as JSON alone knows them and types that you invent in your API, because JSON first-class types actually map onto the use of both RDF literal types _and_ JSON-LD machinery like the values for `@container` and so forth. (While I agree with @ericprud that the use of `@type` is confusing, I don't think it beats out the use of `@container` to govern (JSON) types and shapes for raw confusion-generating power.)

I realize that we are well down the road on this question, but one principle I would offer is that whatever we do should, as much as possible, make the JSON first-class types map _more_ cleanly and simply. Ideally, this would be both in instances and contexts. It would be nice to be able to say that a context author should use features A and B to to map any JSON first-class type (whether it be a string, a number, or an object) and features X and Y to map API-specific types (which we secretly know are much more likely to become `rdf:type`s). I'm not a JSON maven at all, but I suspect that that's the closest thing there is in JSON to the literal datatype/`rdf:type` distinction in RDF, and I'm sure we all agree that if we are going to get people less confused, it behooves us to try to meet them where most of them are.

**Comment by ajs6f** [comment] 2018-11-12 15:32
> To put it another way, if JSON-LD expands to expose Web developers to all of RDF's features, then we will have failed.

To me this seems a bit exaggerated. If JSON-LD _requires_ Web developers to be exposed to all of RDF's features, we have failed. But _allowing them access_ to those features in as comfortable a way as possible, without requiring devs to be aware of them unless/until necessary, seems like a (difficult but) appropriate goal.

**Comment by msporny** [comment] 2018-11-12 16:17
> To me this seems a bit exaggerated... seems like a (difficult but) appropriate goal.

History is littered with groups of standardization bodies, composed of individuals that are incredibly smart and well meaning, that have ruined entire languages by thinking that they have kept the ergonomics of a language approachable.

I think that you are underestimating how difficult it is to achieve the goal you stated once the language becomes a swiss army knife. JSON-LD was never intended to become a swiss army knife. :)

**Comment by ericprud** [comment] 2018-11-16 06:02
> > To me this seems a bit exaggerated... seems like a (difficult but) appropriate goal.
> 
> History is littered with groups of standardization bodies, composed of individuals that are incredibly smart and well meaning, that have ruined entire languages by thinking that they have kept the ergonomics of a language approachable.

I don't see this as an RDF issue. As a JSON user, I find it confusing that the same keyword is used for structure types and scalar types. Structure type says that an object gets a `{ "type": "schema:Person" }` property and scalar type says that `"2018-11-16T05:53:47.015Z"` must match [`xsd:dateTime`](https://www.w3.org/TR/xmlschema-2/#dateTime). They're distinct in every format and programming language (except partially in Java where native scalar types have structure type homonyms, but that's even more confusing).

**Comment by msporny** [comment] 2018-11-17 03:18
@ericprud wrote:
> structure types and scalar types .... must match xsd:dateTime ... except partially in Java where native scalar types have structure type homonyms

Yeah, man... this proves my point. You're way more knowledgeable than 99.99% of the people out there that use JSON. I mean, let's be honest, you're easily like top 25 on the planet when it comes to understanding all of this stuff. :)

I don't expect 99.99% of JSON developers to need to use `@value` and `@type` together. In fact, if there WAS a `@datatype`, I'd expect them to accidentally use it when trying to set a structure type way more often than correctly use it by pairing it with `@value`.

**Comment by ericprud** [comment] 2018-11-17 14:06
Flatterer!

Every JSON user knows the difference between an object `{ "year": 2018, "month": 11, "day": 16 }` and and a scalar `"2018-11-16"`. At issue is whether they find it more or less confusing if we conflate the keywords describing them.

**Comment by ajs6f** [comment] 2018-11-17 15:05
I'm a little troubled by how much comment on this ticket aims to speak for "JSON users" or "JSON developers". That seems a bit "low-res" to me. There are many different overlapping categories of JSON users. Someone trying to stick a stanza of SEO metadata in their home-hosted blog isn't the same as someone trying to consume a semantically-enabled JSON API isn't the same as @danbri's folks isn't the same as someone trying to write a context for their long-established API, and none of these activities look all that much like [WoT](https://www.w3.org/WoT/WG/). 

It may be that I worry too much about this sort of "representational" issue, but I'd appreciate it if, for this issue, we could all be as precise as possible when we discuss user needs or knowledge and specify as much as possible beyond "JSON users" or "JSON devs"...

**Comment by msporny** [comment] 2018-11-17 15:40
> be as precise as possible when we discuss user needs or knowledge and specify as much as possible beyond "JSON users" or "JSON devs"

My perspective is one of lowest common denominator and the biggest user community that we have right now, and that's schema.org. I always think about how a feature is going to impact them, and if there is a non-trivial possibility that it will be negative, then it's a strike against the feature in my mind. Everyone else is secondary because they usually have the motivation and background to dig in and try to really understand at depth. I'm not worried about the people at the "expert" level of the spectrum, because they will be able to figure it out. I do worry about the folks in the middle, who know just enough to really get them into trouble... especially if there is a large selection of footguns to pick from that are just barely under the surface of JSON-LD.

... but all this is going to be vague and theoretical until we have a specific feature to talk about.

**Comment by ajs6f** [comment] 2018-11-17 17:29
I understood us to be talking about the feature discussed in this ticket (`@datatype`) and I admit I don't see how it affects many people using schema.org. Most of them are using a provided context, not writing their own. The (many fewer) who are incorporating schema.org vocab into some other context certainly fall out of your "lowest common denominator" category, do they not?

**Comment by msporny** [comment] 2018-11-17 17:52
> The (many fewer) who are incorporating schema.org vocab into some other context certainly fall out of your "lowest common denominator" category, do they not?

Yes, which means we're debating a feature that the vast majority of people using JSON-LD (that I think the language is primarily designed for) will never see or touch. It's solving a problem that they don't have... and introducing it may have the unintended consequence that @BigBlueHat raised above -- higher cognitive load when learning the language AND misuse of `@datatype`.

**Comment by ajs6f** [comment] 2018-11-17 17:57
The vast majority of people using JSON-LD will never write their own context, but I'm sure you agree that we don't want to put _any feature that is useful mostly for context-authors_ out of scope for discussion.

**Comment by gkellogg** [comment] 2018-11-17 19:04
I think further discussion is somewhat muted by my interpretation of the recent WG discussion and the content of PR #92. Although the [original discussion](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-11-09-json-ld#section3-1) was about introducing `@datatype` (something which is steeped with many issues of backwards compatibility), the [direction of the group](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-11-09-json-ld#resolution2) was to improve the discussion on uses of `@type` to help clarify when it can be used, and that it does have different uses:

<blockquote>
<p><strong>Rob Sanderson:</strong> 1.7 is fine. 4.2.1 needs more clarity<br>
… it is not a technical issue it is a learning/implementation issue<br>
… 4.2 is the problem<br>
… splitting out @type into how to use for Classes and for Literals</p><p><strong>Gregg Kellogg:</strong> what about further definition of other keywords</p><p><strong>Rob Sanderson:</strong> a section in 9 about keywords and gives full definition.</p><p><strong>Benjamin Young:</strong> more than happy to help rewording. confusion between Value instead of Literal.</p><p><strong>Ivan Herman:</strong> we should make is more explicit that there is very clear distinction between classes and literals in JSON-ld</p><blockquote class="proposed_resolution">
  <p><strong>Proposed resolution: bigbluehat &amp; gkellogg to come up with rewording for 4.2, and new section for 9 for keywords, for review as to whether this will solve confusion without technical change</strong> <em>(Rob Sanderson)</em></p>
</blockquote>
</blockquote>

After a couple of small changes, I intend to merge that PR without closing the issue, and we'll see where we are after that.

**Comment by gkellogg** [comment] 2018-11-17 19:13
Regarding what constituency JSON-LD serves, in my opinion, the landscape has changed markedly since the original recommendation was made: JSON-LD is a fundamental part of the web, and we need to consider the experience of those communities. JSON-LD is also seeing substantial new deployment opportunities, where the appeal is definitely that it is JSON, but there is a stronger need to use rich semantic expressiveness (@ajs6f noted WoT, but also Publishing, and Verifiable Claims).

I believe that it's necessary to express pretty most all of RDF in JSON-LD, and the specs need to make this clear. In fact, since adding support for lists of lists, we can pretty much do that. I don't think that the Syntax document should be weighed down with these bits, but they do require introduction, examples, and the normative grammar to describe them.

JSON-LD has been an enormous success, and we don't want to screw that up, but we also have a somewhat different value-proposition now, and groups formerly foreign to the idea have, in fact, become more educated (witness the SEO community's work in adopting JSON-LD and semantics). Of course there remain JSON constituents that are not (yet) on board with JSON-LD, but [recent discussions at the TAG](https://github.com/w3ctag/design-reviews/issues/312#issuecomment-434689623) indicate a broad appreciation for what JSON-LD may be able to do for the web platform.

**Comment by gkellogg** [comment] 2018-11-17 19:56
Pulled #92 which addresses this issue. Requires WG action to close the issue.

**Comment by iherman** [comment] 2018-12-08 05:53
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-12-07-json-ld#section4).

- `RESOLVED:  close issues 56, 77, and 102 as having been addressed by recent merges`
<details><summary><i class="differentiate">View the transcript</i></summary>
Gregg Kellogg: issue 56 - this was looking for examples to indicate unexpected behavior when type is a vocab<br/>
… i think ball was in Ivan’s court whether the examples were sufficient<br/>
… we are not closing the issue until after the PR, so question is whether we are ready to close<br/>
… we added 2 examples<br/>
… next issue is 77, disambiguate uses of @type<br/>
… Webex seems to have some problems with this meeting, especially if changing focus on my computer<br/>
… we discussed adding @datatype, instead decided to add text around different uses of @type<br/>
… are people satisfied with wording?<br/>
Gregg Kellogg: use of @none regarding language<br/>
… in seeming conflict with requirement that language has to be string, @none didn’t specify<br/>
… fixed that wording making clear that @none has to be a string<br/>
Benjamin Young: these are tagged proposed closing<br/>
… we need to decide if ready to close<br/>
Adam Soroka: I wanted to mention the @datatype issue - I’m okay with this, but we may need a gitHub tag for whenever issues about @type comes up<br/>
… this will be a way to verify that spec wording update is enough to minimize confusion<br/>
Gregg Kellogg: <a href="https://github.com/w3c/json-ld-wg/issues/24">https://github.com/w3c/json-ld-wg/issues/24</a><br/>
Gregg Kellogg: I did raise issue 24 about surfacing the minutes on this topic like we did in Community Group<br/>
… could we do this?<br/>
… was useful in community group<br/>
Ivan Herman: minutes cleanup is done by me, and summarizing each meeting may not be a good idea<br/>
Gregg Kellogg: there is a scribe tool that builds summaries and indexes automatically<br/>
Benjamin Young: it works on issues and action lists at top/bottom of each meeting minutes<br/>
Gregg Kellogg: the good thing is it aggregates all minutes on each issue<br/>
Benjamin Young: I will take an action to investigate to see if we can build index of minutes by issue<br/>
… I think this is a good idea<br/>
Gregg Kellogg: will work with bigbluehat on this since I worked on CG<br/>
Benjamin Young: can we close these 3 issues<br/>
… 56, 77 and 102 ?<br/>
Ivan Herman: can we do a resolution to close these 3 issues?<br/>
Proposed resolution: close issues 56, 77, and 102 as having been addressed by recent merges (Benjamin Young)<br/>
Ivan Herman: +1<br/>
Gregg Kellogg: +1<br/>
Tim Cole: +1<br/>
Benjamin Young: +1<br/>
David Newbury: +1<br/>
Pierre-Antoine Champin: +1<br/>
Resolution #1: close issues 56, 77, and 102 as having been addressed by recent merges<br/>
</details>

**Closed by iherman** 2018-12-08 05:53 UTC
Labels: needs discussion, propose closing, spec:editorial
