### ISSUE TITLE
@none for language maps clarification

### ISSUE THREAD

**Issue by azaroth42** [w3c/json-ld-syntax#102] opened 2018-12-05 18:20 UTC
In https://www.w3.org/TR/json-ld11/#language-indexing, it says:

> ... the special index @none is used for indexing data which does not have a language ...

Is that a string that really has no language (e.g. just a random set of characters) or can it be a string that is not known to have a language, but might in practice?

**Comment by iherman** [comment] 2018-12-08 05:54
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-12-07-json-ld#section4).

- `RESOLVED:  close issues 56, 77, and 102 as having been addressed by recent merges`
<details><summary><i class="differentiate">View the transcript</i></summary>
Gregg Kellogg: issue 56 - this was looking for examples to indicate unexpected behavior when type is a vocab<br/>
… i think ball was in Ivan’s court whether the examples were sufficient<br/>
… we are not closing the issue until after the PR, so question is whether we are ready to close<br/>
… we added 2 examples<br/>
… next issue is 77, disambiguate uses of @type<br/>
… Webex seems to have some problems with this meeting, especially if changing focus on my computer<br/>
… we discussed adding @datatype, instead decided to add text around different uses of @type<br/>
… are people satisfied with wording?<br/>
Gregg Kellogg: use of @none regarding language<br/>
… in seeming conflict with requirement that language has to be string, @none didn’t specify<br/>
… fixed that wording making clear that @none has to be a string<br/>
Benjamin Young: these are tagged proposed closing<br/>
… we need to decide if ready to close<br/>
Adam Soroka: I wanted to mention the @datatype issue - I’m okay with this, but we may need a gitHub tag for whenever issues about @type comes up<br/>
… this will be a way to verify that spec wording update is enough to minimize confusion<br/>
Gregg Kellogg: <a href="https://github.com/w3c/json-ld-wg/issues/24">https://github.com/w3c/json-ld-wg/issues/24</a><br/>
Gregg Kellogg: I did raise issue 24 about surfacing the minutes on this topic like we did in Community Group<br/>
… could we do this?<br/>
… was useful in community group<br/>
Ivan Herman: minutes cleanup is done by me, and summarizing each meeting may not be a good idea<br/>
Gregg Kellogg: there is a scribe tool that builds summaries and indexes automatically<br/>
Benjamin Young: it works on issues and action lists at top/bottom of each meeting minutes<br/>
Gregg Kellogg: the good thing is it aggregates all minutes on each issue<br/>
Benjamin Young: I will take an action to investigate to see if we can build index of minutes by issue<br/>
… I think this is a good idea<br/>
Gregg Kellogg: will work with bigbluehat on this since I worked on CG<br/>
Benjamin Young: can we close these 3 issues<br/>
… 56, 77 and 102 ?<br/>
Ivan Herman: can we do a resolution to close these 3 issues?<br/>
Proposed resolution: close issues 56, 77, and 102 as having been addressed by recent merges (Benjamin Young)<br/>
Ivan Herman: +1<br/>
Gregg Kellogg: +1<br/>
Tim Cole: +1<br/>
Benjamin Young: +1<br/>
David Newbury: +1<br/>
Pierre-Antoine Champin: +1<br/>
Resolution #1: close issues 56, 77, and 102 as having been addressed by recent merges<br/>
</details>

**Closed by iherman** 2018-12-08 05:54 UTC
Labels: propose closing, spec:editorial

**Comment by BigBlueHat** [comment] 2018-12-13 19:42
By way of connecting dots, this clarification also makes the closing of #91 more obvious.
