### ISSUE TITLE
Alternative support for list-like structures such as schema:ListItem

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-syntax#15] opened 2018-06-30 16:27 UTC
Per a suggestion by @danbri, we may want to add a container type, similar to `@list` for encoding things like [`schema:ItemList`](http://schema.org/ItemList) serializations, when the values are [`schema:ListItem`](http://schema.org/ListItem) and order is set through `schema:position`. `ItemList` can be used with text values as well, but this is already reasonably supported natively.

```json
{
  "@context": {
    "@vocab": "http://schema.org/",
    "itemListElement": {
      "@container": {
        "@type": "@itemList",
        "@itemType": "http://schema.org/ListItem",
        "@itemProperty": "http://schema.org/itemListElement",
        "@itemPosition": "http://schema.org/position"
      }
    }
  },
  "@type": "ItemList",
  "@url": "http://en.wikipedia.org/wiki/Billboard_200",
  "name": "Top music artists",
  "description": "The artists with the most cumulative weeks at number one according to Billboard 200",
  "itemListElement": [
    {"@type": "MusicGroup", "name": "Beatles"},
    {"@type": "MusicGroup", "name": "Elvis Presley"},
    {"@type": "MusicGroup", "name": "Michael Jackson"},
    {"@type": "MusicGroup", "name": "Garth Brooks" }
  ]
}
```

Original issue [Native support for schema:ListItem #595](https://github.com/json-ld/json-ld.org/issues/595)

**Comment by iherman** [comment] 2018-08-28 18:59
I must admit I do not really understand this. Can someone shiw what that thing woukd mean in Turtle?

**Comment by ajs6f** [comment] 2018-08-28 19:06
@iherman The original ticket has examples that were useful to me.

**Comment by azaroth42** [comment] 2018-08-29 15:48
The issue is whether or not we can make it easier for ordered entries to be represented as arrays in JSON-LD, rather than only rdf:List.  For example [schema](https://schema.org/) has an `ItemList` that contains `ListItem`s, the [Ordered List Ontology](http://smiy.sourceforge.net/olo/spec/orderedlistontology.html) has an `OrderedList` with `Slot`s, and [OAI-ORE](http://openarchives.org/ore/1.0/datamodel) has an `Aggregation` with `Proxy`s. 

If the only value that these resources are adding is the ability to express an order, and JSON-LD is not ontology specific (e.g. we don't otherwise give (much) preference to RDF/RDFS terms over any others) then it would be valuable to allow a context to express that the json array should be treated as a`schema:ItemList` rather than an `rdf:List`, with all of the equivalent blank nodes hidden in the machinery.

**Comment by ajs6f** [comment] 2018-08-29 15:55
I've seen this come up in cultural heritage work in particular, where (e.g.) OAI-ORE is particularly important.

**Comment by iherman** [comment] 2018-08-30 12:49
Thanks @ajs6f to push me to do my homework and read the original issue:-)

I do feel a bit uneasy about this...

- I realize that the point on ordering in schema.org _is_ a real issue in practice. We did hit the problem in the [Publication Manifest](https://www.w3.org/TR/wpub/) work because, for example, the order of authors of a paper is obviously important. 
- I also realize that the native (ie, triple level) representation of RDF lists is, to say the least, awkward.

However... the awkwardness of RDF lists is mostly hidden to all users because it is relatively easy to handle them with the usual RDF serializations (including JSON-LD) maybe with the exception of RDF/XML when literal values are used. Ie, on the user level lists are fine, and the usual underlying machinery (SPARQL and others) can handle them already. The problem I see in JSON-LD+schema.org seems to be inherent to schema.org insofar as they shied away to include, say, an "authorList" property that would behave exactly like "author" except that the JSON-LD `@context` file would include the `@list` container statement. Ie, we have to be careful introducing new features...

That being said, I also see the value of the [proposal](https://github.com/json-ld/json-ld.org/issues/595#issuecomment-368239449) of @dlongley (or the [alternative version thereof](https://github.com/json-ld/json-ld.org/issues/595#issuecomment-368258625) of @gkellogg). I just wonder whether other, similar "patterns" may come up for other structures that would lead to a similar template because, after all, we are talking about baking in some sort of a template into JSON-LD...

**Comment by gkellogg** [comment] 2018-08-30 22:34
Perhaps @danbri can common on the actual utility for schema.org use cases.

**Comment by azaroth42** [comment] 2018-08-31 17:15
Following discussion on WG call 2018-08-31, the current thinking is to close `wontfix`.  The complexity of the work is high, the value is circumstantial on the ontology following a particular design pattern, it would be out of synch with other RDF serializations, and the scope is sliding towards manipulation of triples rather than serialization of them.

Combined with a `wontfix` for #7, I think we can propose a new design guideline of:

> Describe serialization of graphs, not transformation of graphs.

or similar.

@danbri If this is still an important use case for schema.org, please can you weigh in before 2018-09-07? Thanks!

**Comment by azaroth42** [comment] 2018-09-13 17:02
On the WG call of 2018-09-07, we [resolved](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-09-07-json-ld#resolution4) to close this issue, won't fix.

The rationale, following that of #7, is that this is data transformation not simple mapping and is out of scope.  Further, the use case has not been validated and out of band discussions on the topic lead us to believe it's no longer desirable.

**Closed by azaroth42** 2018-09-13 17:02 UTC
Labels: spec:enhancement, spec:substantive, spec:wontfix
